apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yada-application 
spec:
  project: default
  source:
    repoURL: https://github.com/Oran901/redis-webapp.git
    targetRevision: HEAD 
    path: webapp 
  destination:
    server: https://kubernetes.default.svc
    namespace: yada 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
