apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "commonLabels" . | indent 4 }}
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }} 
